### ISSUE TITLE
add payout prefrences

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#11]
To Do:

- [ ] Remove req. paypal email address before adding listing
![2017-02-20_17-10-56](https://cloud.githubusercontent.com/assets/10249755/23141950/ab9def70-f78f-11e6-91cb-b9b864472a92.png)

- [ ] Add payout preference page in admin where client can choose, Wire, paypal or Western Union as seen in video illustration. (be advised: while we obtain contracts with western union and wire company, we will advise client (if wire) of a $75 USD administration fee and fees their banks might impose (if western union) western union fee + $25 USD administration fee)

**and require the following data for wire:**
Wire Currency:
Wire threshold (dropdown choice: 100,250,500,1000,2500) (Tip field: "Since there is a fee per wire, please select amount at which you want us to wire your earnings")
Bank Name:
Bank Account Name:
Bank Address:
Bank Phone:
Bank Swift
Bank Routing number:
Bank IBAN (if in Europe)

**If western union:**
Currency:
Threshold (dropdown choice: 100,250,500,1000,2500) (Tip field: "Since there is a fee per wire, please select amount at which you want us to wire your earnings")
Full Name
Phone number
Address
City and State

**Comment by mnights101** [comment]
![airbnb-payout-preferences-set](https://cloud.githubusercontent.com/assets/10249755/23141760/bcb928f2-f78e-11e6-88df-f12461c659b0.gif)

**Comment by mindrootstech** [comment]
In backend, there are commision, site charges and tax as well

There will be 2 cases for refund:
1. Host cancelled booking
2. User cancelled booking

I will just need amount to be refunded in both cases please.
Will it be Amount paid - taxes, Amount paid - site charges/commision?

i think if host cancels, user should be refunded full as its not the user's mistake.

**Comment by mnights101** [comment]
**# If User cancels:**

We will go with the Flexible Cancellation Policy: in all cases BNBfusion fees and fees are non-refundable:

Cancellation Policy (to be displayed on site):

**## Flexible: Full refund 1 day prior to arrival, except fees**

- Cleaning fees are always refunded if the guest did not check in.
- The Bnbfusion service fee is non-refundable.
- Accommodation fees (the total nightly rate you're charged) are refundable in certain circumstances as outlined below.
- If there is a complaint from either party, notice must be given to Bnbfusion within 24 hours of check-in.
- Bnbfusion will mediate when necessary, and has the final say in all disputes.
- A reservation is officially canceled when the guest clicks the cancellation button on the cancellation confirmation page, which they can find in Dashboard > Your Trips > Change or Cancel.
- Cancellation policies may be superseded by the Guest Refund Policy, extenuating circumstances, or cancellations by Bnbfusion for any other reason permitted under the Terms of Service. Please review these exceptions.
- Applicable taxes will be retained and remitted.

If Host cancels:

**Comment by mnights101** [comment]
**# If host cancels**

What happens if my host cancels my reservation?
If your reservation is canceled by your host you'll have two options:

Transfer your payment to a new Bnbfusion reservation
Get a full refund
Note: In the event that your reservation is more than 4 weeks away, your payment will be automatically refunded.

Transfer your payment to a new Bnbfusion reservation

If you choose this option, the money you paid towards your initial reservation is immediately available to use towards a new reservation. Once you've found a new place, we'll automatically transfer your original payment to your new reservation request, along with any eligible credit from Bnbfusion.

Get a full refund

If you don't want to book another place on Bnbfusion, you can ask for a full refund. To get a refund:

Log in to your Bnbfusion account from a computer
Go to Your Trips
Find your canceled reservation
Click Request a refund
Refunds can't currently be requested using the Bnbfusion apps or mobile website.

**Comment by mnights101** [comment]
Few mispellings here:

instead of guests you put quest's
on next page under wire transfer: description reads "their bank" when it should read "your bank"
