### ISSUE TITLE
Increase Ranges in a few places

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#13]
- [ ] Increase range for search from 10+ to 5000+ and let client increase or decrease from there.
![price-range](https://cloud.githubusercontent.com/assets/10249755/23325199/f5432900-fac9-11e6-9d8a-30d829226751.png)

- [x] Increase bedrooms right now max bedrooms is 6 set to 16 bedrooms

- [x] Increase beds to 16 beds

- [x] Bathroom ranges 1, 1.5,2,2.5,3,3.5 etc, all the way till 16 baths max

- [x] Property description character count raise to 500 characters max.

**Comment by mindrootstech** [comment]
Task complete.
Everything except for bathroom ranges was easy. For .5 bathroom values, the logic of code implemented had to be edited across create, update and search.
Total Effort - $70

**Comment by mnights101** [comment]
I suspect this issue is also related to recent front end work

**Comment by mindrootstech** [comment]
How did this come up?
Can you list the steps as above work is not related to this in any way.

**Comment by mnights101** [comment]
I just went to the front page and there it was. I believe it occured when you were making changes related to this issue.

**Comment by mindrootstech** [comment]
This should be resolved now.
Please clear cache once before reviewing.
