### ISSUE TITLE
PAID VIA UPWORK -  -Messaging system not functional

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#14]
When you click on contact host in any particular listing, when you click submit. The email that I get as admin reads "you got message"

and then it reads the message sent, however, it does not say what "user" it was sent from.therefore there is no way to reply to it.

All messages to host should get auto screened for phone numbers and websites (if present they should be censored), a copy should be stored in admin inbox.

**Comment by mindrootstech** [comment]
Marco,

Please let me know What edits you want to the email being recieved to host.
Also, admin right now has no inbox.. So that will have to be created from scratch if required. Please confirm.

Also, for screening, we can screen for mobile numbers and websites/email addresses and if found, should the message not be sent or should the message be sent but not received and admin to be notified?

**Comment by mnights101** [comment]
- [ ] All emails will be logged in Admin Inbox

- [ ] Host will receive an email with filtered message

- [ ] Host also has inbox at bnbfusion and can view and reply email on there as well.

- [ ] Host can reply to client directly via email, reply from both parties is also logged as conversation in admin inbox

- [ ] System will censor any phone number, emails, or websites. additional censored words may be added to system later as we monitor conversations.

- [ ] Please design contact flow exactly as shown in the video with instant book upsell if available.

**Please issue ETA and quote for approval.**

![contact-host](https://cloud.githubusercontent.com/assets/10249755/23489714/54804ba6-feca-11e6-8fd6-82250d814e7b.gif)

**Comment by mindrootstech** [comment]
Hi Marco,

For this task, we will do the following:
1. Change design of Contact Host popup to have dates and guests displayed (same as AirBNB) plus also have the upsell instant booking option if active for property.
2. Censor the data for any phone number, emails, or websites. Notify admin via email if any user uses censored data.
3. When a message is sent, Change design of email sent to host acc to Airbnb (email recieved from you already but will need content for links in bottom part like FAQs etc)
4. Change design of email for message sent from host to user (design required)
5. Create an admin module in backend where admin can view all messages between users and also a module to show alerts for messages with censored data.

Right now, reply to emails directly to log message in system wont work as that required a full -fledged email server setup. To reply, user/host has to login into his/her account and go into messages/inbox and reply from there.

Total cost for above specified work: $400
If there is any deviation, please let me know.
Else, let me know when we can start this.

**Comment by mnights101** [comment]
Please proceed

**Comment by mnights101** [comment]
Manik,

I do not see the contact us button in any listing. It seems to have disappeared (see screenshot):
![2017-04-12_11-02-56](https://cloud.githubusercontent.com/assets/10249755/24964599/b3c5b5f4-1f6f-11e7-8abe-123fcf24f1a5.png)

**Comment by mindrootstech** [comment]
This has been completed marco.
Please approve and release milestone.

**Comment by mnights101** [comment]
Manik, do you QA before you release work?, because this "contact us" issue is riddled with bugs.

1- [ ] when not logged in, it will ask you to log in, however when you log in, it does not proceed to contact us page it just logs you in and that's it. it should proceed to flow into the contact us page after log in.

2- [ ] travel dates are not relayed into contact page travel dates, therefore client must reenter the dates (very redundant)

3- [ ] The contact us page does not resize correctly in different screen sizes

4- [ ] Under profile on contact us page, it says "Tell Cameron a little about yourself" this should be a dynamic field to change Cameron to whatever the hosts name is., same goes for the New York text this should be dynamic to wherever the city the listing is in.

5- [ ] when you send the message it tells you this is an instant book listing, you can book it now, but the only option is a button that says forget it,there should be a book now button as well, just like in the video above, and the text does not match, it should all match.

6- [ ] recieved email all links are broken, and I cannot reply to this message, nor am I told how to reply to this message. The travel dates and checkout dates are merged together, very confusing.


7- [ ] In admin area add dates to messages

8- [ ] sender and receiver username are the same in admin area.

**Comment by mindrootstech** [comment]
Hi Marco,

Points 1, 2, 3, 4, 5, 7 and 8 are fixed.
For point 6, i have specified above that reply only works after you login into the system and revert a message. If you want that mentioned in the email somewhere, please provide the specific text and it will be updated in the email accordingly. Also, the email has a lot of links from airbnb whoch we dont know where they should lead on our website. I had asked you but you told me to keep them blank targetted for now.
If you can get me URLs for all the links in the email, i will get them updated as well.

**Comment by mnights101** [comment]
Please give me an update on point 5, Last I checked the Instant book button was removed.

**Comment by mindrootstech** [comment]
Marco,

I had updated you on Skype as well.
The instant book button only comes for listings which have instant booking enabled.
When we bulk updated listings, none of them had instant booking enabled.
Please update a listing for instant booking and try, it will have the instant book button come up after contact.
Let me know if you see any issues.

**Comment by mnights101** [comment]
Here are the links to enable in the email:

https://www.bnbfusion.com/user/help/view/8
https://www.bnbfusion.com/user/help/view/9
https://www.bnbfusion.com/user/help/view/10

Contact us: https://lc.chat/now/8618524/1

**Comment by mnights101** [comment]
Manik,

have the links been enabled in the emails? So we can close this out?

**Comment by mindrootstech** [comment]
Yes Marco, The links have been updated in the emails.

**Comment by mnights101** [comment]
Manik, the emails I am getting from users contacting property owners have several issues which do not allow me to respond , nor understand which property they are referring to, In order to fix this bug I need the following tasks performed:

- [ ] In admin dashboard and client dasboard enable links to user profile and receiver profile

- [ ] in notification email, when I click reply I should be able to reply to sender of email, therefore email should be clients email.

- [ ] Property image in email should link to property in question page

- [ ] In admin dashboard and client dashboard add and enable property in question link

**Comment by mindrootstech** [comment]
Hi Marco,

Please find my comments against the tasks specified:
1. In admin dashboard and client dasboard enable links to user profile and receiver profile -> **Currrently, we dont have any user profile pages in our entire system. So, where should the link to the user profile take a user to?**

2.  in notification email, when I click reply I should be able to reply to sender of email, therefore email should be clients email. -> **THIS CAN BE ACHIEVED.**

3. Property image in email should link to property in question page ->  **THIS CAN BE ACHIEVED.**

4. In admin dashboard and client dashboard add and enable property in question link  ->  **THIS CAN BE ACHIEVED.**

5. In https://www.bnbfusion.com/user/messages/inbox page messages should be in order of latest to past dates, currently they are all scrambled unordered, please view illustration B  ->  **THIS CAN BE ACHIEVED.**

6. In users messaging system there should be a link to property in question, please view illustration C   ->  **THIS CAN BE ACHIEVED.**

7. Please set default image profile of users who have not uploaded their photo to this thumbnail: ->  **THIS CAN BE ACHIEVED.**

For all achievable tasks, total effort will be $150.
Please suggest for Point1.
Waiting for approval.

**Comment by mnights101** [comment]
please proceed with this issue

**Comment by mindrootstech** [comment]
Please suggest for Point 1 so we can finish all tasks in this issue in 1 go.
Also, pending approval on Tasks #26 and #31

**Comment by mnights101** [comment]
for point 1, this is a user profile page https://www.bnbfusion.com/profile/NC01MjE=
Therefore we do have user profiles.

As for receiver profile this is the same as user profile.

**Comment by mnights101** [comment]
paid via upwork for extra work
