### ISSUE TITLE
Phone sms verification hook up to twilio

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#15]
setup phone verification:
![twilio](https://cloud.githubusercontent.com/assets/10249755/23342901/cebb0576-fc38-11e6-8fd8-986a79b82861.png)

https://www.twilio.com/login

use and pass sent via upwork

**Comment by mindrootstech** [comment]
Right now, when an account is created, user is not asked for mobile number.
Its only when user goes into profile and tries to update that mobile number verification comes into picture. Do you want to change this flow or maintain it and just implement twilio to send verification SMS?

**Comment by mnights101** [comment]
Manik,

I would like all users to verify their mobile numbers, I already see a few fake profiles being added.
it looks like we are going to need sms verification. We will put this issue on the backburner, till we get the bulk upload out of the way. This may interfere with that, correct?

**Comment by mindrootstech** [comment]
Yes, thats correct.
Lets put this on the burner till we finish import.

**Comment by mnights101** [comment]
please quote this.

**Comment by mindrootstech** [comment]
We will change process where:
1. After sign up, user is asked to select country and enter mobile number.
2. If mobile number exists, error is shown and user is asked to login from existing account or enter another mobile number.
3. After successful validation of unique mobile number, SMS with 6 digit code will be sent by twilio.
4. User will be prompted to enter the code on screen. If correct, user profile will be created. Else, not.

Total effort - $280

**Comment by mnights101** [comment]
actually no, That is not how airbnb process works, sms is not mandatory for sign ups, it is mandatory for property listing, I will send you a video of the process.

**Comment by mindrootstech** [comment]
Thanks for the approval Marco. Will get the work started.
For future reference, pasting the Twilio creds here:

username: mnights@tutanota.com
password: $5iFvq&5AoKu

Needs to support all countries supported by Twilio.

**Comment by mindrootstech** [comment]
Hey Marco,

We have completed the task on local using a dummy Twilio account.
But to get it live for you to check and close, Twilio is asking us to purchase a number to send messages from  and it will have to be a US number.
Can you please login into Twilio and purchase a number of your liking.
The cost is 1-2$ per month but you can choose a number of your liking.
Let me know once you are done please.

Tried contacting on Skype as well a few days back.
