### ISSUE TITLE
optimize DB

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#18]

**Comment by mindrootstech** [comment]
Database has been optimised for 4 tables of amenities and images table.
Before optimisation, each of the 4 amenities tables had around 7,00,000 records each which have been reduced to 1,00,000 records.

For images table, there were 35,00,000 records which have been reduced to approx 1,00,000 records.

Cost: $250

**Comment by mnights101** [comment]
Load time is so long , I went to another website. The site looks to be broken to be honest with you, The search results are inaccurate now, I search Punta Cana, and I get New Mexico Texas listings.
Please check to see where you guys went wrong here and adjust accordingly.

**Comment by mindrootstech** [comment]
Load time is not related to this task.
We just optimised the Amentities and photos table as per what was expected.
Load time and search time will be managed as part of a seperate task.

Even for search, the script had a default search algirithm where it searches acc to lat/long and not place name etc.
So if there is a property within its radius even within another city, it displays the results. All of these can be handled by us as part of a seperate task but we havnt touched search or page load times in this project till now.

**Comment by mnights101** [comment]
paid via upwork
