### ISSUE TITLE
Maps and search result not displaying relevant locations

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#19]
this was working, and now it has been broken.

**Comment by mindrootstech** [comment]
I just did a search in Punta Cana and only got results there. Screenshot attached.
![screen shot 2017-04-27 at 2 44 49 pm](https://cloud.githubusercontent.com/assets/19343942/25476544/26932cbc-2b58-11e7-9d15-5eaf5c8a93ec.png)

**Comment by mindrootstech** [comment]
This has been fixed up.
Please check and close.
