### ISSUE TITLE
searching and viewing property

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#2]
When I enter location Santo DOmingo from the index page (home) and enter calendar dates, it says no properties available, however when you move the price range down from 280 to 10 then property appears.

Please set this to auto set at a lower range of 10 USD not current 280

**Comment by mindrootstech** [comment]
Issue has been resolved.
$280 was setup static in code in a lot of places for filters and has been updated to $10 everywhere.

Effort - $40

**Comment by mnights101** [comment]
This has been paid via upwork milestone one (add chat script) and added bonues of 29 USD to cover the total of 40 USd charged on this job
