### ISSUE TITLE
update site with new logos

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#20]
Manik, I setup new logos on admin ,however they are not appearing in chrome and the.ico is still the bird, please update with respective images below:

[b_b_fusion_wEB_icon.ico.zip](https://github.com/BNBFuse/milestones/files/974430/b_b_fusion_wEB_icon.ico.zip)
![icon-only-length-web-black1](https://cloud.githubusercontent.com/assets/10249755/25677387/bd76e366-3013-11e7-9551-3c7b2d451e17.png)
![bnbfusion-oficial-icon-white-back](https://cloud.githubusercontent.com/assets/10249755/25677394/c4f5a0b4-3013-11e7-9ba5-cd620d9565ea.gif)

**Comment by mindrootstech** [comment]
Logo has been updated in Favicon, all browsers and emails as well.
Total Effort: $20

**Comment by mnights101** [comment]
Manik, the .ico should be transparent background, right now it has a white background.

**Comment by mindrootstech** [comment]
Was previously uploaded as was provided by you with white background.
Has been updated to transparent background.

**Comment by mnights101** [comment]
paid via upwork
