### ISSUE TITLE
slow search - speed up

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#21]
Effort quoted 180

Manik, the ajax is still loading very slow, on my first search it loaded quickly, then subsequent searches the page loaded quickly but the ajax was slow, very slow now.

**Comment by mindrootstech** [comment]
Hi Marco,

The search speed has been further increased and is now taking only 3-4 secs max.
Also, the listing details page has been optimised to the max possible.

Total effort for this task: $320

**Comment by mnights101** [comment]
Please fix the google auto suggest it seems to have been disabled.

**Comment by mindrootstech** [comment]
Just checked and auto suggest seems to be working fine.
![screen shot 2017-05-10 at 10 53 17 am](https://cloud.githubusercontent.com/assets/19343942/25884302/ee363636-356e-11e7-9c59-55774586a499.png)

**Comment by mnights101** [comment]
paid via upwork
