### ISSUE TITLE
create thumbnails for faster load

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#22]
currently site image of listings are loading rather slow, please implement thumbnails to speed up image load time.

**Comment by mindrootstech** [comment]
Tasks to be done:
1. Create script to create and upload thumbs of property images on S3
2. Run script for all 1,00,000+ properties
3. Load thumb images on Search results to increase image load speed.

Total Effort: $240

**Comment by mnights101** [comment]
Will thumb be created on every new property added to the website automatically thereafter?

**Comment by mindrootstech** [comment]
Yes of-course.
Please approve so work can be started.

**Comment by mnights101** [comment]
approved

**Comment by mindrootstech** [comment]
Marco,

Work has been completed and image thumbs are now being loaded.
Please check and let me know so we can close task.

**Comment by mnights101** [comment]
paid via upwork
