### ISSUE TITLE
create sitemap

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#23]
In this issue we need two tasks resolved:

1. - [ ] We need a dynamic sitemap that will show all countries - cities - then listings
just like airbnb sitemap
https://www.airbnb.com/sitemaps
![sitemap](https://cloud.githubusercontent.com/assets/10249755/26430575/55800cb0-40bc-11e7-95c7-3c1a47415d06.gif)

2. - [ ] this sitemap should also be  available as google xml format url, ie. bnbfusion.com/sitemap.xml

Please quote and issue ETA

**Comment by mindrootstech** [comment]
Marco,

To create a web sitemap like Airbnb, it will be a cost of $180

Creating a dynamic XML sitemap will not be that straight forward as there will be a lot of records.
airbnb also does cached and compressed sitemap in XML - https://www.airbnb.com/sitemap-p2.xml.gz 2017-05-31T23:29:33+00 ...
Here, there is one sitemap, which contains URLs of hundreds of sub sitemap zip files, each of which contains further URLS.
To implement something like this, it would easily take a cost of around $600.
Not sure if that would be worth it.

Another way is that we maintain a sitemap of listing URLs only in a sitemap xml file and keep concatenating every new entry to it. This way, the sitemap will keep getting updated with all new listings but if ever a listing is removed, then it will still remain in the sitemap. The cost to do something like this will be $200

**Comment by mnights101** [comment]
OK to be clear, for 200 I get the sitemap, layout pages as displayed above in airbnb animated gif (web pages) viewable at bnbfusion.com/sitemap and a sitemap.xml file for google webmaster tools submission (ie. bnbfusion.com/sitemap.xml)?

**Comment by mindrootstech** [comment]
No Marco,

Airbnb like web sitemap cost is $180

Additionally, if you want a static sitemap xml file with concatenating URLs, that will be additional $200.
If you want a full dynamic sitemap in XML with compression like airbnb, that will be additional $600.

Let me know how you want to proceed with this.

**Comment by mnights101** [comment]
Airbnb like web sitemap cost is $180
+
static sitemap xml file with concatenating URLs, for additional $200. Approved

**Comment by mindrootstech** [comment]
Hi Marco,

The task has been completed.
Web sitemap URL - https://www.bnbfusion.com/sitemap (Also has been added to website footer)

XML sitemap -https://www.bnbfusion.com/sitemap.xml

**Comment by mnights101** [comment]
good job 380 paid via upwork
