### ISSUE TITLE
QA- No book now button on city specific landing page mobile

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#24]
When surfing from mobile and landing on page: 
https://www.bnbfusion.com/search/Punta%20Cana,%20La%20Altagracia%20Province,%20Dominican%20Republic?lat=18.5820101&long=-68.4054729&checkin=06/06/2017&checkout=06/15/2017&guests=1

View actual visitor recording facing issue:
https://insights.hotjar.com/p?site=412004&recording=671046448&token=752621a6d60e58abcec79835b3f45d24

Instead of viewing More filters button turn more filters into a small link above newly created "Search" button

**Comment by mnights101** [comment]
Yes, I understand we obviously assume to scroll down, But there are too many clients making the same mistake, Please adjust the mobile view (will provide airbnb land page mobile view example shortly)

**Comment by mnights101** [comment]
This is what airbnb mobile view looks like
![0-eus-d2-b3cebec06493260e1fe692268379c399](https://cloud.githubusercontent.com/assets/10249755/26645617/ab811da8-4606-11e7-8b0d-9c89d6b26abd.jpg)

Please adjust our mobile view to match screenshot.
Please quote and issue ETA before commencing work.

**Comment by mindrootstech** [comment]
Marco,
In the screenshot, there is a switcher for map and list whereas in our case, only list shows.
Do you want the map view to show in our case?

Also, we can match top bar but our functionality will be acc to our site and will drop to show the fields being shown directly on top of page (Screenshot attached).

This means the top bar view will be like airbnb with everything collapsed by default but when you click on it, our view with location, guests and type selection will come up so the functionality is consistent with desktop experience. 

+ Ajax reload will have to be implemented on change in search criteria.

Effort:
In case map switch is also needed - $350
In case only top bar needs to be redesigned - $200

**Comment by mnights101** [comment]
let's go with Map switch and match top bar functionality.
350 approved

**Comment by mnights101** [comment]
need to get chat button out of the way to test map filters

**Comment by mindrootstech** [comment]
The chat button has been removed in mobile views.

**Comment by mindrootstech** [comment]
Hi Marco,

Can we clear this milestone on upwork and close it off?

**Comment by mindrootstech** [comment]
Hi Marco,

Have been trying to catch up on Skype for a few days now.
Can you please review and close out #23 and #24 so we can proceed with next tasks.
Please send me an update.

Thanks in advance

**Comment by mnights101** [comment]
Manik,

The filters are not working correctly still on this,, If I select 1 bedroom it shows me all condos with 1,2,3,4,5,6 and even 8 bedrooms.

**Comment by mindrootstech** [comment]
Marco,

Thats how the filters were working right form start.
I have got the full site QA started off and this will come up as a part of the issues in it and then we can plan on how and what all to resolve there.
