### ISSUE TITLE
map zoomed out on listing view

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#26]
https://insights.hotjar.com/p?site=412004&recording=719018181&token=1f782828c830a81adc6d717a379f7800

Manik, for some reason when clients visit the listings page map is zoomed way out by default, please set default map view zoom level cover the entire city client is searching for

**Comment by mindrootstech** [comment]
The map has been like this right form the start and hasnt been worked upon. So cannot be marked as a bug.

We will have to update the code for the map and make it more dynamic in terms of load zoom acc to the search results.

Right now, even if you search for US and then zoom in and then move to the next page, the map doesnt move along to show the new results. that will also have to be implemented.

Effort: $180
Please approve.

**Comment by mnights101** [comment]
![zoom-map-git-issue](https://user-images.githubusercontent.com/10249755/27843501-539a1616-60e2-11e7-9328-df452766e861.gif)

- [ ] map will be zoomed in to cover city area

- [ ] when you hover over the listing it will highlight marker on map

- [ ] "search as I move the map" checkbox will be selected by default

- [ ] As map is zoomed visible listings in map view will be displayed on listings and listings not in map view will be withdrawn from listings as shown in video

- [ ] when listing map marker is selected, it will pop up a quick preview screen as illustrated in video

- [ ] each quick preview pop up is clickable to listing page

We can match functionality for 180 as quoted above?

**Comment by mnights101** [comment]
ok, please proceed with this feature. what is your ETA to complete?

**Comment by mnights101** [comment]
any updates here?

**Comment by mindrootstech** [comment]
Hey Marco,

To implement the above 6 tasks, We will have to edit the entire map code to make it much more dynamic and responsive according to the airbnb website reference.

Total effort: $250

**Comment by mnights101** [comment]
Please proceed, what's the eta?

29. Jan 2018 04:53 by notifications@github.com:

**Comment by mindrootstech** [comment]
Hi Marco,

All the 6 listed tasks for the map have been completed and moved to live.
Please clear cache and check and let me know.

We should be good to start work on the next task. Please allot that as well.

**Comment by mnights101** [comment]
please match the map listing markers as displayed: in other words instead of current map icon, replace with price label marker map icon as seen above in demonstation video.

**Comment by mnights101** [comment]
approved

**Comment by mindrootstech** [comment]
Marco,

The markers have been made dynamic. Please check and confirm.
