### ISSUE TITLE
Can't add a listing due to email verify bug

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#28]
Manik,

I registered as a new user and at no time during the sign up did they system inform me I needed to verify my email. In addition I did not recieve any email notification to verify my email address.

This feature was indeed working in the beginning and now it is not working. Please fix this issue.

![cant-add-listing-before-email](https://user-images.githubusercontent.com/10249755/28883229-a640b30c-777b-11e7-9dd4-36c39bf38b57.png)

**Comment by mindrootstech** [comment]
![2](https://user-images.githubusercontent.com/19343942/29212055-3659ed60-7eba-11e7-95a3-e864e98e256d.png)

![4](https://user-images.githubusercontent.com/19343942/29212047-3095e776-7eba-11e7-8342-ba7325c82bf8.png)
Hi Marco,

I just got this checked out.
First of all, the verify email is coming on creating a new account with a link to verify the account.
Attached screenshot of that.

So, to make it clear to the user, we have now added a message on new sign up saying - 
"Hosts and guests on site are real people with real homes. That’s why you’ll have to confirm your email address before you can add a new listing. Please check your email and verify it."

This will make it more clear that the user has to verify their email.
![1](https://user-images.githubusercontent.com/19343942/29212035-2588dd66-7eba-11e7-8966-9e4f6a23cc1f.png)

**Comment by mnights101** [comment]
Correct, however this email was never sent by the system. That is why I labeled it a bug.


11. Aug 2017 07:56 by notifications@github.com:

**Comment by mindrootstech** [comment]
Can you check again now.
We did 3 test account sign ups and got the email every single time.

**Comment by mnights101** [comment]
Please add this text and resend functionality link as illustrated in image below:
![cant-add-listing-before-email](https://user-images.githubusercontent.com/10249755/29497006-85daf998-85ad-11e7-8642-238064044749.png)
