### ISSUE TITLE
booking notifications

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#31]
we received a booking and no notifications were received by either property host nor client who placed booking

![bnb-booking](https://user-images.githubusercontent.com/10249755/36151194-bda229b2-109c-11e8-8df6-249e1e996dce.png)

Tasks:

- [ ] Fix client notification

- [ ] Fix property owner notification

- [ ] Add admin notification

- [ ] Add Booking details and notification on client dashboard and admin dashboard index page

**Comment by mindrootstech** [comment]
Hey Marco,

We can setup email notifications for Client, Property owner and even admin when a property is booked.
I will need reference email templates that need to be sent out to all users.
Also, we can have a notification with a badge on client and admin dashboard for new booking confirmations.
If there is a problem in email delivery, its best to use SendGrid (https://sendgrid.com/) or any other 3rd party SMTP service.

Total effort: $260
Please confirm and provide reference templates + sendGrid account (or any other SMTP details)

**Comment by mindrootstech** [comment]
To implement SMS notifications as well, we can use Twilio to do the same.
Extra effort for that will be $50.
Total will come to $310

Please confirm

**Comment by mindrootstech** [comment]
Hi Marco,

Awaiting Sendgrid (or any other preferable SMTP account) account details and the email templates to be sent out.

**Comment by mindrootstech** [comment]
Any update on above??

**Comment by mnights101** [comment]
smtp account posted in upwork messages

**Comment by mnights101** [comment]
I cannot seem to locate an airbnb booking confirmation, will have to wait for a reservation to come through, in the mean time please use message notification templates and make sure it includes data in the following image

![bnbfusion-temp-booking](https://user-images.githubusercontent.com/10249755/36494785-83a96a90-1709-11e8-8854-27d5c4773375.png)

**Comment by mindrootstech** [comment]
Hi Marco,

The task has been completed.
We have fixed the booking email notification to client and host + added an email to admin.
Also, we have created a menu item in client login - My reservations and in that, we have added a View details button showing all the info in a new details page. This will be for the host
Same for Guest in My Trips.

In admin backend, we have created a new module - Booking reservations and linked to a view page.
Plus Twilio has been setup to send Text notification and SendGrid to send email notifications.
Everything is on live now.
Please check and let me know.

**Comment by mnights101** [comment]
please make these final changes and I will proceed to QA task:
![better-adminview-bookings](https://user-images.githubusercontent.com/10249755/36804622-7e2e6240-1c91-11e8-8502-83a44c97fd25.png)

**Comment by mindrootstech** [comment]
Hi Marco,

The above changes have been made.

**Comment by mnights101** [comment]
when trying to set [property](https://www.bnbfusion.com/user/listing/view/MTA5ODI2Xzc1ODk=) to $1 dollar, I can't get past this page below:
![bnbfusion-error-in-booking-process](https://user-images.githubusercontent.com/10249755/38176931-0c074418-35c6-11e8-8e18-d9985d28b8de.png)


I keep clicking save and it won't go past this page:
I also tried to click time frame for booking periods and I get this error message " Maximum stay should be less than no of booking days" This should not be per days booked this should be per hosting period booked, in other words host can set a booking time frame per season, and should not be correlated per client booking. Please fix this error as well.

**Comment by mnights101** [comment]
paid via upwork milestone 3
