### ISSUE TITLE
User Property listing and administration Add delete property and breadcrumb in property edit page

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#37]
use airbnb style

**Comment by mnights101** [comment]
add delete method to properties

**Comment by mnights101** [comment]
search task:
![search-bar-listings](https://user-images.githubusercontent.com/10249755/59513816-9dc35a00-8e89-11e9-9b3a-a47e231cd3f3.png)

**Comment by mindrootstech** [comment]
Marco,

Both Search and Delete functionality in Active listings has been implemented.
Please review and close.
Cost - $60

**Comment by mnights101** [comment]
funded on upwork via milestone number 36
