### ISSUE TITLE
New listing added

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#38]
For every new property added to the systems the following processes shall occur:

- [x] 1. New property will be listed in the admin index page 

- [x] 2. Property listed notification will be sent to admin and host via email

- [x] 3. A tweet will be posted to our twitter account with description and 1 picture @bnbfusion

- [x] 4. Instagram of new property will be posted with 1 picture  username: bnbfusion777

**Comment by mindrootstech** [comment]
Tasks to be done:
1. Create a View Listings module in admin backend -
Listing Name, No of rooms and bathrooms, price, host name (with link to host profile), date created and link to view property page in new tab.
2. Ability to search for listing in backend by name and host name
3. Send notification email to admin on new listing
4. Create tweet with description and image on new listing
5. Create instagram post with 1 image of new listing

Total effort: $300
Please confirm

**Comment by mnights101** [comment]
Please proceed

**Comment by mindrootstech** [comment]
Can you please provide me the login details for the instagram and twitter account to generate the API keys.

**Comment by mindrootstech** [comment]
Marco,

The task has been completed.
Please review so the task can be closed out.

**Comment by mnights101** [comment]
I do not see a new module in admin dashboard that show latest properties listed,
I do not see any twitter nor instagram post of new properties

**Comment by mindrootstech** [comment]
Here is a screenshot showing where the module is.



Also if you create a new listing now, it will go to your account feed. We had done all tests on our accounts.

**Comment by mnights101** [comment]
Manik, When I said admin dashboard I meant on the index page of dashboard, the screenshot that you sent this was already there prior, and that listing creation dates are not even set.

**Comment by mindrootstech** [comment]
Marco,

It wasn’t clear that you needed a dashboard widget. And this module has been created and wasn’t existing before.

Moving it to dashboard shouldn’t be a problem as we will port the code to a dashboard widget.
The date isn’t set for all old listings and we have fixed that as well. Any new listings will now have a created date showing.

Will update you tomorrow once the dashboard widget is created.

**Comment by mindrootstech** [comment]
Marco,

The widget on the dashboard has been created.
Right now, the created date will be blank as all old listings didnt have any created date saved in the database.
Any new listings created now onwards will show the created date as well.

**Comment by mindrootstech** [comment]
Please have a look at insta and twitter accounts now.
We have created a few new listings and all have been posted.
You can also try to create a new listing. We have added a error log file to check for any errors coming up during posting to Insta or twitter when you create a new listing.

**Comment by mnights101** [comment]
On Instagram post, please include a link to listing and description
![instagram-link-and-description-missing](https://user-images.githubusercontent.com/10249755/40568336-038ae59a-6048-11e8-88a9-600ede751eb8.gif)

**Comment by mindrootstech** [comment]
The description has been added to instagram post.
A link is not allowed in instagram, so that request has been omitted.
