### ISSUE TITLE
error spotted on instant book

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#39]
When I clicked contact host on a instant book property, I was notified by the cms I could book instantly and contacting host is not required, on this pop is where the error is, the button should read "Instant Book" not "Instant Host"

![2018-05-18_09-57-54](https://user-images.githubusercontent.com/10249755/40238862-6fa095c0-5a82-11e8-8593-d33ab692bdcd.gif)

**Comment by mindrootstech** [comment]
No prob. Will get his updated today.

**Comment by mindrootstech** [comment]
Text has been updated.
Please review and close

**Comment by mnights101** [comment]
When trying to recreate this error, The errorshas been fixed, however I also notice there is no confirmation that the message has been sent. Which leaves the user wondering if the message was sent at all

**Comment by mnights101** [comment]
ok
