### ISSUE TITLE
Add rollbar

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#4]
rollbar credentials: https://rollbar.com/onboarding/BNBfusion/integrate/?framework=php

user: info@bnbfusion.com
pass: mia209gt

**Comment by mindrootstech** [comment]
Rollbar added for PHP and Javascript both.
Effort: $30

**Comment by mnights101** [comment]
Rollbar not alerting on errors
![500-error](https://cloud.githubusercontent.com/assets/10249755/22900700/a5ffd0a4-f205-11e6-9b11-ed2b3fb83b69.png)

**Comment by mindrootstech** [comment]
Fixed.
The error was being generated by rollbar library only and hence wasnt being recorded.
The entire library had to be modified to implement across project properly and log all sorts of errors.
Additional effort: $20

Total effort: $50
