### ISSUE TITLE
Add house rules and display rules and policies on all listings page

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#40]
- [x] Task 1
create Rules page in add property wizard as displayed in image illustration below, client admin area, this will be required information on all properties, default settings for all properties will be
1. suitable for children 2-12= yes
2. suitable for infants= yes
3.suitable for pets = no
4. smoking allowed=no
5. events or parties allowed= no

![add-house-rules-page-in-listing-process](https://user-images.githubusercontent.com/10249755/40505909-be664b38-5f63-11e8-8aeb-beeb11ce8a92.gif)

- [x] Task 2 
Display house rules, check in time frame and checkout.... and cancelation policy on all listing pages: listing example: https://www.airbnb.com/rooms/975964

![new-feature-to-add-rules-andpolicies-onpropertypage](https://user-images.githubusercontent.com/10249755/40506020-144165ce-5f64-11e8-8342-c841ec099be3.gif)

**Comment by mindrootstech** [comment]
Effort: $220
Please confirm

**Comment by mnights101** [comment]
approved

**Comment by mindrootstech** [comment]
Marco,

The task has been completed.
Please review

**Comment by mnights101** [comment]
Task 1: On house rules page, These are yes no question, however the options displayed are on/off which do not make sense.

Task 2: I do not see house rules nor do I see check in time range and check out times displayed in property listing page

**Comment by mnights101** [comment]
As stated in task 1, default settings for all properties (this means properties already uploaded) will be:
default settings for all properties will be:

suitable for children 2-12= yes
suitable for infants= yes
3.suitable for pets = no
smoking allowed=no
events or parties allowed= no

Please add these settings to all properties already uploaded.
Also keep in mind default settings encompass default check in time range, which was handled in another github issue. This default checkin and checkout should already be set to all properties.

**Comment by mindrootstech** [comment]
Marco, The default values have been setup now so all properties will be showing the values now unless edited.
