### ISSUE TITLE
Anonymous checkout

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#41]
Manik,

Recently we received a complaint when we sent a client to book a property on the website, they said they had to register,  and I instantly thought of the hotels.com checkout process, Instead we do not demand client to log in, the login will be optional..However we will capture enough data during registration to register user and create a temp password for them sent via email.

Tasks to complete:

1. - [x]  optional login will be placed on checkout page as displayed in video
1. - [x]  non logged in data will be requested on checkout page
1. - [x]  breakup checkout page in 3 steps as displayed in video
1. - [x]  readd paypal checkout option

**Comment by mnights101** [comment]
![anonymous-checkout](https://user-images.githubusercontent.com/10249755/43332568-b1e9cd02-9196-11e8-8924-991ae7d2fc73.gif)

**Comment by mindrootstech** [comment]
Hi Marco,

We can get this done as required.
Tasks:
1. Remove mandatory login pop-up on Confirm booking button
2. Have optional sign in on checkout page
3. Have extra fields like Name and email in Checkout form.
4. If user is doing guest checkout, take those fields and create the user in backend, create a temp password for user and send in new welcome email.
5. If user is logged in, skip Step 2 and name fields.

Effort: $380
Let me know if approved to be done.

**Comment by mnights101** [comment]
approved, please proceed.

**Comment by mindrootstech** [comment]
Hi Marco,

The task is complete and moved to live.
Please verify the same.

Also, to update you, no emails are going out of the server due to a failed invoice on SendGrid. You should clear that out to get the emails working.

![screenshot-app sendgrid com-2018 09 10-17-54-14](https://user-images.githubusercontent.com/19343942/45298656-d1eaa280-b526-11e8-88fb-be1022682dcd.png)

**Comment by mnights101** [comment]
Manik,

- The sendgrid issue has been resolved.
- On mobile view  the website is still demanding  registration
- still not seeing paypal payment option
-please number steps and separate as shown in gif animation

**Comment by mnights101** [comment]
P.S. : this listing https://www.bnbfusion.com/user/listing/view/MTA5ODg1XzQ5NjA= doe snot show up in search results when not logged in, can you see why that is?

**Comment by mindrootstech** [comment]
Marco,

The following things have been done:
1. Mobile view fixed
2. Steps numbered
3. Country field moved

Paypal will come when we work on its individual task. The paypal API got updated and hence the old integration is no longer working right now.

For the listing, the listing price is $5 and the filter base amount is set to $10. Hence, it doesnt show up in search results. :)

Please check and let me know on this and which next task to proceed on.

**Comment by mnights101** [comment]
Manik,

- [ ] when signed in as shown in gif video there are 3 steps showing , However on bnbfusion, when signed in only step2 is shown, we should at least shoq two steps. Signed in steps should be as follows:

Step 1: Room details (To make this relevant step 1 should be relabeled "Guest Detail"  (here we display full name  email and mobile phone number, or capture if not signed in)
Step 2: Payment details

- [ ] Another issue I notice is when I try to pay with Bitcoin in mobile view, It will not display Barcode

**Comment by mindrootstech** [comment]
Marco,

The pointed out issue has been resolved.
Also we checked the mobile view and the bar code seems to be loading fine.
Screenshot attached.

![screenshot_20180915-121217_20180915_121228874](https://user-images.githubusercontent.com/19343942/45584423-c0bbe000-b8f0-11e8-9244-f924d0299f10.jpg)

**Comment by mindrootstech** [comment]
Marco, Any update on this?
Can we close this and move on to next task?

**Comment by mnights101** [comment]
solved and paid via upwork

**Comment by mindrootstech** [comment]
Marco,

I recieved the email on guest checkout.
Attached screenshot.

Also, we have added labels for mobile view.
Please review.

![screenshot 2018-10-26 at 12 24 54 pm](https://user-images.githubusercontent.com/19343942/47549622-3cf70980-d91a-11e8-9c3a-ffd584e4c07c.png)

**Comment by mnights101** [comment]
Thanks
