### ISSUE TITLE
Change picture galleries display engine

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#43]
The current galleries are not usable to clients, and are not rendered correctly cropping out most pictures

a suitable gallery  engine will solve these issues:

- [x]  1.  Mobile view friendly
- [x]  2. auto view all pictures can be stopped
- [x]  3. Pictures do not get cropped out

**Comment by mindrootstech** [comment]
So, for this, we can change the gallery pop-up to a different plugin which is both mobile responsive and in which pictures get auto-adjusted and dont crop out.

The top part of the page will remain as it is. We will remove the big image in bottom part and make all squares(which will adjust image in middle).
Once clicked, the new gallery module will open and it will show images in full size without them being cropped and ability to manually scroll to next without autoscroll.

Effort: $80
Please approve.

**Comment by mindrootstech** [comment]
Gallery has been changed
Please review.
URL - https://www.bnbfusion.com/user/listing/view/NTgyNjJfMTQzMw==

**Comment by mnights101** [comment]
Great Job here. Thanks
