### ISSUE TITLE
install new Maps API and places

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#44]
https://console.cloud.google.com/google/maps-apis/api-list?project=bnbfusion-159313

**Comment by mindrootstech** [comment]
Effort to implement new Google map and places API will be $70.
Please approve.

**Comment by mindrootstech** [comment]
Marco,

I'll need to account login and password to get the keys.

**Comment by mindrootstech** [comment]
Completed.
Please review and close.

**Comment by mnights101** [comment]
tasks: 

- [ ] Remove spaces from map icon pop up
![no-space-map](https://user-images.githubusercontent.com/10249755/47176761-6d202600-d2e4-11e8-8792-49042de263df.png)

- [ ] As I hover on map icon listing used to highlight
now it does not even highlight map icon, please return highlights
![no-sync-on-map-hover](https://user-images.githubusercontent.com/10249755/47176975-08190000-d2e5-11e8-84bd-ec7007f25228.png)

- [ ] As I click on map icons, they remain open, this should close automatically when I click on new map icon
![2018-10-18_14-49-51](https://user-images.githubusercontent.com/10249755/47177011-31d22700-d2e5-11e8-8588-2bdc9567eb3c.png)

- [ ] Fix overlapping labels
![2018-10-18_14-51-16](https://user-images.githubusercontent.com/10249755/47177075-5e863e80-d2e5-11e8-8162-dfa15f53149d.png)

**Comment by mindrootstech** [comment]
All these points have been fixed.
Please clear cache and check once.

**Comment by mnights101** [comment]
great Job, Thanks :)
