### ISSUE TITLE
Aesthetics Minor changes, Profile Icons in Pics, No Slide, Maps on off feature

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#45]
In this issue we will make minor changes to UI
TO DO:

1- [ ] **Remove Profile Pics from main lisitings page**
![remove-profile-pics](https://user-images.githubusercontent.com/10249755/45626270-1b724a80-ba5d-11e8-92f7-d5a102646bf0.jpg)

2- [ ] Main Listings images will not slide images anymore
![no-slide](https://user-images.githubusercontent.com/10249755/45627912-f1bb2280-ba60-11e8-8aa6-7f57dac535d3.gif)

3-- [ ] add review count and review icon stars along with cancelation policy in listings display- display cancelation text only if "free cancelation" is offered
![review-display](https://user-images.githubusercontent.com/10249755/45628311-d00e6b00-ba61-11e8-947f-13da43e5e8b0.jpg)

**Comment by mindrootstech** [comment]
Effort: $60.
Please approve

**Comment by mindrootstech** [comment]
Thats fixed.
Please check and approve.

**Comment by mnights101** [comment]
Great Job, Thanks
