### ISSUE TITLE
Add details to profile view

### ISSUE THREAD

**Issue by mindrootstech** [BNBFuse/milestones#48]
On https://www.bnbfusion.com/profile/MjM4LTczNg== Profile page, can you make this display the Country, State and City, Also can you have it display "About me filed that is filled out in member profile.
plus 5 recent reviews and 5 recent properties.

Use this format - https://www.airbnb.com/users/show/4312681
![whatsapp image 2018-11-20 at 10 30 05 pm](https://user-images.githubusercontent.com/19343942/48789998-5f5f2580-ed14-11e8-93f2-58465b98c0ec.jpeg)

**Comment by mindrootstech** [comment]
Marco,

Profile page has been updated as per requirements and has been checked in mobile responsive view as well.
Please reivew: https://www.bnbfusion.com/profile/Ni0zMjQ=

Effort: $70

**Comment by mnights101** [comment]
paid out via upwork  milestone 17
