### ISSUE TITLE
photo upload process revamp

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#49]
Manik,

I want the photo upload process to match airbnb as depicted in screencast.

![airbnb-photo-upload](https://user-images.githubusercontent.com/10249755/51183229-fd034b00-18a6-11e9-8927-7cb268a8d560.gif)

To Do List:

- [ ] match airbnb ux as depicted in screencast

- [x] accept all upload formats .png, jpeg, jpg etc.

- [x] on hover of photo you can see a trash can and on click it will delete photo

- [x] drag and drop rearrange photos

- [x] add another photo empty slot with plus sign

- [x] first photo is cover photo and can be dragged and rearranged

- [x] Upload status on each photo as depicted in screencast

**Comment by mnights101** [comment]
Please proceed, Do you have an ETA on this?

**Comment by mnights101** [comment]
Manik, 

On testing when I tried to upload the first time all there were many duplicates of each photo, and the second time most photos did not appear: https://www.bnbfusion.com/user/listing/view/MTA5OTI1XzM4OTM=

**Comment by mindrootstech** [comment]
Marco,

A file got missed up while uploading.
Please clear cache once and review again.

**Comment by mnights101** [comment]
Paid via upwork milestone 18
