### ISSUE TITLE
Setup Up Paypal

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#5]
Looking into adaptive payments in the mean time please setup App ID
, for the paypal setting page in admin.

let me know if you need my credentials again?

**Comment by mnights101** [comment]
Manik,

Please log into our paypal account and submit adaptive payments app. for approval, I cannot figure out how or where to do that.

**Comment by mindrootstech** [comment]
Please provide Paypal credentials

**Comment by mnights101** [comment]
credentials sent via upwork
