### ISSUE TITLE
SEO work:  URL restructure and reviews serp

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#50]
Manik

for SEO purposes I would like perform all the tasks below: specifically to rename all URL's to reflect the following structure
state/city/category/listing title the category will be listing type ie: Villa, Bungalow, shared room, hostal

To do:

- [x] Restructure all URLS like this: bnbfusion.com/state/city/category/listing title

- [x] add nearby neighborhoods in footer on each listing page relevant to it's location:  we refer to as towns ie. State: FL , City Miami, Town/Neighborhood: South Beach
![github-seo-work](https://user-images.githubusercontent.com/10249755/51389682-7bf4bf80-1b03-11e9-8316-6d8f0dfe6937.png)

- [ ] Convert from stackpath to faslty cdn
https://manage.fastly.com/auth/sign-in
credentials sent via whats app

**Comment by mindrootstech** [comment]
Marco,

For the new URLs, we will be able to achieve this format: bnbfusion.com/listing/state/city/category/listing title

Tasks to be done:
1. Write scripts to change all URL slugs for all lsitings
2. Implement redirects in htaccess file to make new URLs work
3. Create a db of all states and cities with geo-location based on script
4. Implement nearby places lsiting above footer in listing details
5. Convert from stackpath to faslty cdn

Total effort to achieve all 3 tasks will be $325.
Please approve.

**Comment by mnights101** [comment]
Manik, Sorry please add this to task. Place This code on each listing page it will create a review count on google search results. let me know extra fee, I will add it as bonus

`

<script type="application/ld+json">
--
  | {
  | "@context": "http://schema.org",
  | "@type": "LodgingBusiness",
  | "name": "add property title here",
  | "description": "add description here. ...",
  | "petsAllowed": add true or false here,
  | "image": "add cover photo url here",
  | "aggregateRating": {
  | "@type": "AggregateRating",
  | "bestRating": 5,
  | "ratingValue": add property rating digit here,
  | "reviewCount": add numeric review count here
  | },

` Please be sure to test this with google schema test tool: https://search.google.com/structured-data/testing-tool

**Comment by mindrootstech** [comment]
Hi Marco,

All these tasks are done except for the StackPath to Fastly migration.
1. All URLs are updated now
2. Sitemap setup in footer
3. Nearby suggestions at bottom of each listing
4. DB of all ued cities and states wth geo-locations saved
5. Google rating script implemented

Please verify and let me know.
Our total effort for the task has been $350

**Comment by mnights101** [comment]
Requesting the following changes:

- [ ] nearby neighborhoods inaccurate, closer proximity

- [ ] Manik also while checking json integration I notice a terrible error in meta tags, it seems all pages are using the same meta tags from index page. Please make all mets tags specific to listing. Please view screenshot ( give me a quick additional cost on this as well as I will be funding this issue today) 
![meta-changes-bnbfusion](https://user-images.githubusercontent.com/10249755/51861630-19759d80-2313-11e9-9eaf-e26b8b94f3f5.png)

**Comment by mindrootstech** [comment]
Neighbourhood sorting done (Only neighbourhoods with listings in our system show, no all neighbourhoods).
The meta info has also been updated as asked for.
We can forego any fee for the meta task to compensate for the Stackpath one.

**Comment by mnights101** [comment]
funded and paid via milestone 19 on upwork
