### ISSUE TITLE
Regenrate Sitemap.xml

### ISSUE THREAD

**Issue by mindrootstech** [BNBFuse/milestones#53]
1. Rewrite the XML sitemap script.
2. Regenrate the existing sitemap for the new URLs via script.

Effort: $80
Please approve.

**Comment by mnights101** [comment]
manik

Please use structure like airbnb as defined in robots.text
https://www.airbnb.com/robots.txt

Sitemap: https://www.airbnb.com/sitemap-p2-urls-index.xml.gz
Sitemap: https://www.airbnb.com/sitemap-p2_poi-urls-index.xml.gz
Sitemap: https://www.airbnb.com/sitemap-homes_filters_expansion-urls-index.xml.gz
Sitemap: https://www.airbnb.com/sitemap-homes_pdp-urls-index.xml.gz
Sitemap: https://www.airbnb.com/sitemap-seo_events-urls-index.xml.gz
Sitemap: https://www.airbnb.com/sitemap-things_to_do_cities_and_categories-urls-index.xml.gz
Sitemap: https://www.airbnb.com/sitemap-places_pdp-urls-index.xml.gz
Sitemap: https://www.airbnb.com/sitemap-experiences_p2-urls-index.xml.gz
Sitemap: https://www.airbnb.com/sitemap-experiences_pdp-urls-index.xml.gz
Sitemap: https://www.airbnb.com/sitemap-additional_things_to_do-urls-index.xml.gz

**Comment by mindrootstech** [comment]
Marco,

For this, we can follow a structure where the Sitemaps are split as:
Main Sitemap - will contain links to all distributed sitemaps
Site Links Sitemap - links like about us, info links etc
Country and State Sitemap - links with all countries and states links
Listing Sitemaps - these will be multiple listing sitemaps split on google suggested size. So as new listings get added, they will automatically get added to the sitemap and once it becomes bigger than google suggested safe size, a new listing sitemap will be started and automatically added to the main sitemap.

Effort to implement this will be $240.
Please approve.

**Comment by mnights101** [comment]
I have submitted sitemap.  will allow two days to check for erorrs

**Comment by mnights101** [comment]
paid via milesstone on upwork number 21
