### ISSUE TITLE
A user is reporting she cannot complete payment through paypal

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#54]
She was trying to book this property https://www.bnbfusion.com/l/nevada/las-vegas/condo/luxury-wyndham-grand-desert-3-bedroom-2-bath  from 5//2-5/6 

She states: "Hi,
First of all it has taken two days for someone to respond to my questions! I don't know if you need to send me a request to book but when I go to pay through PayPal it says oops! And sends me back to the home page. I'm not sure if I should be trusting the Webb Page?"

Please investigate this issue

**Comment by mindrootstech** [comment]
Hi marco,

I got this checked.
Seems like there was a slight change in paypal checkout process and anew token was needed to be passed to actually make the process complete. I've got it updated now and did a test booking as well.
Should be all good now.
