### ISSUE TITLE
On mobile filters are not working and map view pop up not clickable

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#58]
Manik, when using mobile and selecting filters, I select beachfront properties in Hollywood, Beach, Oxnord California trying to locate a beachfront property I added and the filter does not work.

Also when I used map view to locate this property: https://www.bnbfusion.com/l/california/oxnard/villa/beauty-and-the-beach-hollywood-beachfront-vacation-rental

1. The property does not appear on map
2. The map pop does not stay up and cannot be clicked
3.  mirror fix on erosradar
![pop-up-not-working](https://user-images.githubusercontent.com/10249755/56427796-14c5e300-628b-11e9-8ec9-97c6ac79dd2c.jpg)

Be advised all fixes must be mirrored on erosradar

**Comment by mindrootstech** [comment]
Marco,

These 2 issues have been fixed and pointers have been mirrored to Erosradar as well.

**Comment by mindrootstech** [comment]
The filters on our site are setup such that they work after a bit of delay right from the start.
So after you press apply, wait for it to reload.

**Comment by mnights101** [comment]
- [ ] general location of listing inside listing page has dissapeared

![general0location](https://user-images.githubusercontent.com/10249755/56898941-421b4980-6a60-11e9-9af7-3b1f2fd66219.png)

**Comment by mindrootstech** [comment]
Marco,

I think this was closed a while back.
Can you confirm and close this.
