### ISSUE TITLE
Required Fields Profile page

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#61]
when you click submit , it says fields are required, and we cannot figure out which? please make sure field box turns red and  cation turns red

**Comment by mindrootstech** [comment]
This has been updated now to mark field which are mandatory but not filled up.
Attached screenshot as well.

Effort: $25.
Please approve and close.

![screenshot-www bnbfusion com-2019 05 28-18-32-35](https://user-images.githubusercontent.com/19343942/58480070-2b5b3600-8177-11e9-8596-0ab37fde9977.png)

**Comment by mnights101** [comment]
PAID via upwork milestone 32
