### ISSUE TITLE
Reservations Admin Missing data and search

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#62]
I have an issue on bnb. I am looking for a reservation and cannot find it, it seems we only display in admin area a limited amount of recent reservations with no search option. 

and for some reason on the reservation details there is no guest count, Property owners keep asking how many guests are there.

**Comment by mindrootstech** [comment]
A new module has been created in the backend by the name of Reservations with Search filters and linked to the existing view details. The number of guests has been added to the grid.
In the view details, the No of Guests has been added as well.
Please verify and update.

Effort: $125

**Comment by mnights101** [comment]
Can we get the stripe/paypal  Invoice ID in there I got ID 802 from paypal on booking ID #324
Also there is no way to change booking status.

**Comment by mnights101** [comment]
funded via milestone 31 uppwork

**Comment by mnights101** [comment]
PAID via upwork milestone 31
