### ISSUE TITLE
SMS verification - 2 accounts cannot be confirmed on same phone number

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#63]
Manik,

My secretary now has issues where she need to create a new account with diffrent email, and on old account she verified sms number, can you make the system not worry about the same phone number being on multiple accounts.

**Comment by mindrootstech** [comment]
Marco,

This has been done.
Please check and confirm.
Effort: $25

**Comment by mnights101** [comment]
paid via milestone 35 upwork
