### ISSUE TITLE
Add "Claim Listing" capability

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#67]
For all properties please add "Claim Listing "Functionality, this happens when a property owner sees their listing on our site and they will be able to take control of it.

The listing footer text will read like this:

- [x] Is This Your Listing?

Own or manage this property? Claim your listing for free to respond to reviews, update your profile and much more.
Link: Claim Your Listing

- [x] When they click on link they will be taken to a landing page that looks like this: https://www.tripadvisor.ca/Owners-g154918-d185691-Overlander_Mountain_Lodge-Jasper_Jasper_National_Park_Alberta.html

- [x] When they click  button on landing page, they will be asked to register

- [x] Once logged inn they will continue claim process by filling out this form:

- [x] All form elements will be prefilled with registration data and the property listing in question will be displayed in the form:

![claim-property-bnbfusion](https://user-images.githubusercontent.com/10249755/61674465-f45e5800-acc1-11e9-9d68-61cee10fd3d9.png)

- [ ] - Once they submit admin will receive notification of property claim request, in addition
in admin "add property claims" in navigation and on this page add a list of property claim requests, where I can view submissions and click reject (listing remains unchanged" or accept (listing is transferred over to claimant) here this property is listed in claimants admin panel and removed from current hosters admin panel. 

- [ ] Claimant notification: Claimant will receive an email if we approve or deny , if approved they will get an email informing them of our approval decision and advising them to log in and setup payout fields for proper disbursement.

**Comment by mindrootstech** [comment]
Marco,

As described above, we will follow the flow to do the following tasks:
1. Add a claim listing link to property details page.
2. Create a landing page for claim listings
3, On click of claim listing, open a pop-up with pre-filled data and take a submission.
4. Send the admin a notification of a new request
5. Create a backend module to list and update claims with ability to accept or reject with a reason.
6. In both cases, send an email notification to user with status and reason.

Effort to get this implemented - $450

Questions:
1. Please depict where to put the Is this your listing view in listing details page
2. Please provide content to be put int he claim listing landing page
3. In case there is a pending booking on a listing, can it be transferred? As the payout for the booking will be sent to the owner on booking completion.

Let me know on above so we can start.

**Comment by mnights101** [comment]
1. On footer of this link you can see claim property box: https://www.tripadvisor.ca/Hotel_Review-g154918-d185691-Reviews-Overlander_Mountain_Lodge-Jasper_Jasper_National_Park_Alberta.html

![claim-listing](https://user-images.githubusercontent.com/10249755/62060395-0d4f9780-b1f3-11e9-9c74-6a0ea9ff1fcd.png)

2. https://www.tripadvisor.ca/Owners-g154918-d185691-Overlander_Mountain_Lodge-Jasper_Jasper_National_Park_Alberta.html

3. Pending bookings must be transferred to new owner

**Comment by mindrootstech** [comment]
Task has been completed and moved to live.
Please QA and update.

**Comment by mnights101** [comment]
paid via upwrok milestone 37
