### ISSUE TITLE
admin cancel/refund processing

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#68]
add ability for admin to process a refund/cancelation

- [ ] In admin area add a button "cancel" on reservation details page
when clicked the partial refund process less gateway fees will be initiatiated and host + admin + traveler will be all notified of cancelation via email

![cancel-request](https://user-images.githubusercontent.com/10249755/61744393-3096c480-ad65-11e9-9b2d-71a2ed9c138e.png)

**Comment by mindrootstech** [comment]
Marco,

The task has been completed.
The cancel button is working now in the backend and will process refunds with same process as frontend.
Please verify and close.
Effort: $80

**Comment by mnights101** [comment]
paid via upwork milestone 38
