### ISSUE TITLE
Adding property address

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#7]
- Let client enter address with google map dropdown
- If system cannot locate address show lat and long geo fields or visual map

**Comment by mnights101** [comment]
![airbnb-add-property-entire-process](https://cloud.githubusercontent.com/assets/10249755/22865361/c07f6016-f138-11e6-80f8-d98b7061da22.gif)

**Comment by mindrootstech** [comment]
Work on this task is started and in progress.

**Comment by mindrootstech** [comment]
Hi Marco,

This task has been implemented.
Changes were done in the:
1. Create Listing process
2. A map was implemented in the location screen to drag/drop pointer 
3. In original code, edit listing and create listing were using the same classes which was leading to issues in editing listing. So functions have been duplicated and separated for edit process.

Please review and let me know if there is any feedback.
Effort till now: $200

**Comment by mnights101** [comment]
Manik, when the bulk upload takes place we will be given a .xml or .csv doc. which will contain all fields currently required to add a listing, Please confirm there is a GPS coordinate field or fields in sql database? because, bulk uploader was instructed to provide this data in all listings instead of address fields.

**Comment by mindrootstech** [comment]
Confirmed that there are lat/long fields in database for each property.
