### ISSUE TITLE
Set fields (create listing) to optional

### ISSUE THREAD

**Issue by mnights101** [BNBFuse/milestones#8]
Please change fields settings from "required" to optional.
![fileds-to-optional-1](https://cloud.githubusercontent.com/assets/10249755/23021600/2075f9ca-f423-11e6-9c65-77e256df6e93.png)

**Comment by mindrootstech** [comment]
Task has been completed.

**Comment by mnights101** [comment]
Effort fee?

**Comment by mindrootstech** [comment]
Effort - $20
